apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: virophage
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            securityContext:
              privileged: true
            volumeMounts:
              - name: kvm-host
                mountPath: /dev/kvm
        volumes:
          - name: kvm-host
            hostPath:
              path: /dev/kvm
              type: CharDevice
        nodeSelector:
          dedicated: kvm
        tolerations:
          - key: dedicated
            operator: Equal
            value: kvm
            effect: NoExecute
  healthcheck:
    enabled: false
  image: us.gcr.io/dotted-forest-314903/virophage-challenge:dbdac2761cea003ec040955b79972391d837a37f279e0a3b5b2b4c528494e97d
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: virophage
  labels:
    app: virophage
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`virophage.chal.uiuc.tf`)
      services:
        - name: virophage
          port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: virophage-cname
  labels:
    app: virophage
  annotations:
    external-dns.alpha.kubernetes.io/hostname: virophage.chal.uiuc.tf
spec:
  externalName: traefik.chal.uiuc.tf
  type: ExternalName
