apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: group
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: TCP
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/dotted-forest-314903/group-healthcheck:3b69f04e53afab037357939f74a96d13f5512f1507fe01d8704991cb7e1c97eb
  image: us.gcr.io/dotted-forest-314903/group-challenge:bfa5a0ee24eeccc2a05d09a275b692ed6ec013ca681b3ecf70cbf20f5d5978e1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: group
  labels:
    app: group
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`group.chal.uiuc.tf`)
      services:
        - name: group
          port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: group-cname
  labels:
    app: group
  annotations:
    external-dns.alpha.kubernetes.io/hostname: group.chal.uiuc.tf
spec:
  externalName: traefik.chal.uiuc.tf
  type: ExternalName
