apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: vimjail1
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/dotted-forest-314903/vimjail1-healthcheck:702783e067baf248a81acf6d8b85807334824bd1427e22d0c36ba3d714ae97ff
  image: us.gcr.io/dotted-forest-314903/vimjail1-challenge:94bedb611934b0c782e7b0392874343f33156b8bdba27ab1c570987f137ae35e
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vimjail1
  labels:
    app: vimjail1
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`vimjail1.chal.uiuc.tf`)
      services:
        - name: vimjail1
          port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: vimjail1-cname
  labels:
    app: vimjail1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vimjail1.chal.uiuc.tf
spec:
  externalName: traefik.chal.uiuc.tf
  type: ExternalName
