apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: vimjail2-5
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/dotted-forest-314903/vimjail2-5-healthcheck:974d26a4492bb315547ec01844b5d90beb452e0e6fda9ad60144a394eae9c005
  image: us.gcr.io/dotted-forest-314903/vimjail2-5-challenge:fff8cb4d31d3d26ad3be12d1b38d13b1761a92009b6047ada4d7ab96f7b7621c
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vimjail2-5
  labels:
    app: vimjail2-5
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`vimjail2-5.chal.uiuc.tf`)
      services:
        - name: vimjail2-5
          port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: vimjail2-5-cname
  labels:
    app: vimjail2-5
  annotations:
    external-dns.alpha.kubernetes.io/hostname: vimjail2-5.chal.uiuc.tf
spec:
  externalName: traefik.chal.uiuc.tf
  type: ExternalName
