apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: futuredisk2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: TCP
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            securityContext:
              privileged: true
            volumeMounts:
              - name: fuse-host
                mountPath: /dev/fuse
        volumes:
          - name: fuse-host
            hostPath:
              path: /dev/fuse
              type: CharDevice
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/dotted-forest-314903/futuredisk2-healthcheck:0a78d7eb446a0b10b413406bbb64f44d0116c635dc9d9c38998b7352bc1c0c85
  image: us.gcr.io/dotted-forest-314903/futuredisk2-challenge:957f1433d10fc784499935f5149e94aeeff3448e933af78f575622f93144b1d6
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: futuredisk2
  labels:
    app: futuredisk2
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`futuredisk2-web.chal.uiuc.tf`)
      kind: Rule
      services:
        - name: futuredisk2
          port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: futuredisk2-cname
  labels:
    app: futuredisk2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: futuredisk2-web.chal.uiuc.tf
spec:
  externalName: traefik.chal.uiuc.tf
  type: ExternalName
