apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: zapp-setuid-1
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: false
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            securityContext:
              privileged: true
            volumeMounts:
              - name: kvm-host
                mountPath: /dev/kvm
        volumes:
          - name: kvm-host
            hostPath:
              path: /dev/kvm
              type: CharDevice
        nodeSelector:
          dedicated: kvm
        tolerations:
          - key: dedicated
            operator: Equal
            value: kvm
            effect: NoExecute
  healthcheck:
    enabled: true
    image: us.gcr.io/dotted-forest-314903/zapp-setuid-1-healthcheck:aecf3e73d6d72a2253ce953b3e258b16b95957d5a2404cda9fe79ada7c2c388c
  image: us.gcr.io/dotted-forest-314903/zapp-setuid-1-challenge:a948a290e8698384379fc8a6c48a3d76ea85ace341acd3f38688c341ef71df39
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: zapp-setuid-1
  labels:
    app: zapp-setuid-1
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`zapp-setuid-1.chal.uiuc.tf`)
      services:
        - name: zapp-setuid-1
          port: 1337
  tls:
    secretName: tls-cert
---
apiVersion: v1
kind: Service
metadata:
  name: zapp-setuid-1-cname
  labels:
    app: zapp-setuid-1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: zapp-setuid-1.chal.uiuc.tf
spec:
  externalName: traefik.chal.uiuc.tf
  type: ExternalName
