apiVersion: v1
kind: Secret
metadata:
  name: ctfd-secrets
type: Opaque
stringData:
  SECRET_KEY: REDACTED
  DATABASE_URL: mysql+pymysql://ctfd:REDACTED@REDACTED/ctfd
  REDIS_URL: redis://REDACTED:6379
  AWS_ACCESS_KEY_ID: REDACTED
  AWS_SECRET_ACCESS_KEY: REDACTED
  # Technically AWS_S3_BUCKET is public, but it's easier to yq on this file
  AWS_S3_BUCKET: REDACTED

  # ctfd-discord-webhook-plugin
  DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/REDACTED/REDACTED
  DISCORD_WEBHOOK_CHALL: ''

  # ctfd-discord-auth
  DISCORD_AUTH_WEBHOOK: https://discord.com/api/webhooks/REDACTED/REDACTED
  DISCORD_AUTH_CLIENT_ID: 'REDACTED'
  DISCORD_AUTH_SECRET: REDACTED
